#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Reservation de voitureDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InserttblAccount(tblAccount instance);
    partial void UpdatetblAccount(tblAccount instance);
    partial void DeletetblAccount(tblAccount instance);
    partial void InserttblEmplacement(tblEmplacement instance);
    partial void UpdatetblEmplacement(tblEmplacement instance);
    partial void DeletetblEmplacement(tblEmplacement instance);
    partial void InserttblArrivé(tblArrivé instance);
    partial void UpdatetblArrivé(tblArrivé instance);
    partial void DeletetblArrivé(tblArrivé instance);
    partial void InserttblDepart(tblDepart instance);
    partial void UpdatetblDepart(tblDepart instance);
    partial void DeletetblDepart(tblDepart instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Parking.Properties.Settings.Default.Reservation_de_voitureDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAccount> tblAccount
		{
			get
			{
				return this.GetTable<tblAccount>();
			}
		}
		
		public System.Data.Linq.Table<tblEmplacement> tblEmplacement
		{
			get
			{
				return this.GetTable<tblEmplacement>();
			}
		}
		
		public System.Data.Linq.Table<tblArrivé> tblArrivé
		{
			get
			{
				return this.GetTable<tblArrivé>();
			}
		}
		
		public System.Data.Linq.Table<tblDepart> tblDepart
		{
			get
			{
				return this.GetTable<tblDepart>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAccount")]
	public partial class tblAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tblAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmplacement")]
	public partial class tblEmplacement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Emplacement_No;
		
		private string _Position;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEmplacement_NoChanging(string value);
    partial void OnEmplacement_NoChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    #endregion
		
		public tblEmplacement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Emplacement No]", Storage="_Emplacement_No", DbType="NVarChar(30)")]
		public string Emplacement_No
		{
			get
			{
				return this._Emplacement_No;
			}
			set
			{
				if ((this._Emplacement_No != value))
				{
					this.OnEmplacement_NoChanging(value);
					this.SendPropertyChanging();
					this._Emplacement_No = value;
					this.SendPropertyChanged("Emplacement_No");
					this.OnEmplacement_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblArrivé")]
	public partial class tblArrivé : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nom_du_conducteur;
		
		private string _Voiture_No;
		
		private string _Temps_d_arrêt;
		
		private string _Emplacement_sélectionné;
		
		private string _Category;
		
		private System.Nullable<System.DateTime> _Temps;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNom_du_conducteurChanging(string value);
    partial void OnNom_du_conducteurChanged();
    partial void OnVoiture_NoChanging(string value);
    partial void OnVoiture_NoChanged();
    partial void OnTemps_d_arrêtChanging(string value);
    partial void OnTemps_d_arrêtChanged();
    partial void OnEmplacement_sélectionnéChanging(string value);
    partial void OnEmplacement_sélectionnéChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnTempsChanging(System.Nullable<System.DateTime> value);
    partial void OnTempsChanged();
    #endregion
		
		public tblArrivé()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nom du conducteur]", Storage="_Nom_du_conducteur", DbType="NVarChar(50)")]
		public string Nom_du_conducteur
		{
			get
			{
				return this._Nom_du_conducteur;
			}
			set
			{
				if ((this._Nom_du_conducteur != value))
				{
					this.OnNom_du_conducteurChanging(value);
					this.SendPropertyChanging();
					this._Nom_du_conducteur = value;
					this.SendPropertyChanged("Nom_du_conducteur");
					this.OnNom_du_conducteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Voiture No]", Storage="_Voiture_No", DbType="NVarChar(50)")]
		public string Voiture_No
		{
			get
			{
				return this._Voiture_No;
			}
			set
			{
				if ((this._Voiture_No != value))
				{
					this.OnVoiture_NoChanging(value);
					this.SendPropertyChanging();
					this._Voiture_No = value;
					this.SendPropertyChanged("Voiture_No");
					this.OnVoiture_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Temps d\'arrêt]", Storage="_Temps_d_arrêt", DbType="NVarChar(50)")]
		public string Temps_d_arrêt
		{
			get
			{
				return this._Temps_d_arrêt;
			}
			set
			{
				if ((this._Temps_d_arrêt != value))
				{
					this.OnTemps_d_arrêtChanging(value);
					this.SendPropertyChanging();
					this._Temps_d_arrêt = value;
					this.SendPropertyChanged("Temps_d_arrêt");
					this.OnTemps_d_arrêtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Emplacement sélectionné]", Storage="_Emplacement_sélectionné", DbType="NVarChar(50)")]
		public string Emplacement_sélectionné
		{
			get
			{
				return this._Emplacement_sélectionné;
			}
			set
			{
				if ((this._Emplacement_sélectionné != value))
				{
					this.OnEmplacement_sélectionnéChanging(value);
					this.SendPropertyChanging();
					this._Emplacement_sélectionné = value;
					this.SendPropertyChanged("Emplacement_sélectionné");
					this.OnEmplacement_sélectionnéChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(50)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temps", DbType="DateTime")]
		public System.Nullable<System.DateTime> Temps
		{
			get
			{
				return this._Temps;
			}
			set
			{
				if ((this._Temps != value))
				{
					this.OnTempsChanging(value);
					this.SendPropertyChanging();
					this._Temps = value;
					this.SendPropertyChanged("Temps");
					this.OnTempsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDepart")]
	public partial class tblDepart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Voiture_No;
		
		private string _Conducteur;
		
		private string _Type;
		
		private string _Temps_P;
		
		private System.Nullable<decimal> _Montant;
		
		private System.Nullable<System.DateTime> _Heure_de_départ;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVoiture_NoChanging(string value);
    partial void OnVoiture_NoChanged();
    partial void OnConducteurChanging(string value);
    partial void OnConducteurChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTemps_PChanging(string value);
    partial void OnTemps_PChanged();
    partial void OnMontantChanging(System.Nullable<decimal> value);
    partial void OnMontantChanged();
    partial void OnHeure_de_départChanging(System.Nullable<System.DateTime> value);
    partial void OnHeure_de_départChanged();
    #endregion
		
		public tblDepart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Voiture No]", Storage="_Voiture_No", DbType="NVarChar(50)")]
		public string Voiture_No
		{
			get
			{
				return this._Voiture_No;
			}
			set
			{
				if ((this._Voiture_No != value))
				{
					this.OnVoiture_NoChanging(value);
					this.SendPropertyChanging();
					this._Voiture_No = value;
					this.SendPropertyChanged("Voiture_No");
					this.OnVoiture_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conducteur", DbType="NVarChar(50)")]
		public string Conducteur
		{
			get
			{
				return this._Conducteur;
			}
			set
			{
				if ((this._Conducteur != value))
				{
					this.OnConducteurChanging(value);
					this.SendPropertyChanging();
					this._Conducteur = value;
					this.SendPropertyChanged("Conducteur");
					this.OnConducteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Temps P]", Storage="_Temps_P", DbType="NVarChar(50)")]
		public string Temps_P
		{
			get
			{
				return this._Temps_P;
			}
			set
			{
				if ((this._Temps_P != value))
				{
					this.OnTemps_PChanging(value);
					this.SendPropertyChanging();
					this._Temps_P = value;
					this.SendPropertyChanged("Temps_P");
					this.OnTemps_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montant", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Montant
		{
			get
			{
				return this._Montant;
			}
			set
			{
				if ((this._Montant != value))
				{
					this.OnMontantChanging(value);
					this.SendPropertyChanging();
					this._Montant = value;
					this.SendPropertyChanged("Montant");
					this.OnMontantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Heure de départ]", Storage="_Heure_de_départ", DbType="DateTime")]
		public System.Nullable<System.DateTime> Heure_de_départ
		{
			get
			{
				return this._Heure_de_départ;
			}
			set
			{
				if ((this._Heure_de_départ != value))
				{
					this.OnHeure_de_départChanging(value);
					this.SendPropertyChanging();
					this._Heure_de_départ = value;
					this.SendPropertyChanged("Heure_de_départ");
					this.OnHeure_de_départChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
